// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260830145343_Inventoria_Start")]
    partial class Inventoria_Start
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Classifications.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_category_parent_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_category_slug");

                    b.ToTable("category", "public");
                });

            modelBuilder.Entity("Domain.Classifications.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<Guid?>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("ItemDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_definition_id");

                    b.Property<Guid?>("ItemVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_variant_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PackDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("pack_definition_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tag");

                    b.HasIndex("InventoryId")
                        .HasDatabaseName("ix_tag_inventory_id");

                    b.HasIndex("InventoryItemId")
                        .HasDatabaseName("ix_tag_inventory_item_id");

                    b.HasIndex("ItemDefinitionId")
                        .HasDatabaseName("ix_tag_item_definition_id");

                    b.HasIndex("ItemVariantId")
                        .HasDatabaseName("ix_tag_item_variant_id");

                    b.HasIndex("PackDefinitionId")
                        .HasDatabaseName("ix_tag_pack_definition_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tag_slug");

                    b.ToTable("tag", "public");
                });

            modelBuilder.Entity("Domain.Classifications.TagAssignment", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer")
                        .HasColumnName("entity_type");

                    b.HasKey("TagId", "EntityId", "EntityType")
                        .HasName("pk_tag_assignment");

                    b.ToTable("tag_assignment", "public");
                });

            modelBuilder.Entity("Domain.Inventories.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentInventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_inventory_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_inventory");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_inventory_category_id");

                    b.HasIndex("ParentInventoryId")
                        .HasDatabaseName("ix_inventory_parent_inventory_id");

                    b.ToTable("inventory", "public");
                });

            modelBuilder.Entity("Domain.Inventories.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("asset_number");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("ItemVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_variant_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid?>("PackDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("pack_definition_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("serial_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_inventory_item");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_inventory_item_category_id");

                    b.HasIndex("InventoryId")
                        .HasDatabaseName("ix_inventory_item_inventory_id");

                    b.HasIndex("ItemVariantId")
                        .HasDatabaseName("ix_inventory_item_item_variant_id");

                    b.HasIndex("PackDefinitionId")
                        .HasDatabaseName("ix_inventory_item_pack_definition_id");

                    b.ToTable("inventory_item", "public");
                });

            modelBuilder.Entity("Domain.Items.ItemDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_item_definition");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_item_definition_category_id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_item_definition_sku");

                    b.ToTable("item_definition", "public");
                });

            modelBuilder.Entity("Domain.Items.ItemVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("barcode");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("ItemDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_definition_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_item_variant");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("ix_item_variant_barcode");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_item_variant_category_id");

                    b.HasIndex("ItemDefinitionId")
                        .HasDatabaseName("ix_item_variant_item_definition_id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_item_variant_sku");

                    b.ToTable("item_variant", "public");
                });

            modelBuilder.Entity("Domain.Items.PackDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("barcode");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pack_definition");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("ix_pack_definition_barcode");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_pack_definition_category_id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_pack_definition_sku");

                    b.ToTable("pack_definition", "public");
                });

            modelBuilder.Entity("Domain.Items.PackDefinitionItem", b =>
                {
                    b.Property<Guid>("PackDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("pack_definition_id");

                    b.Property<Guid>("ItemVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_variant_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.HasKey("PackDefinitionId", "ItemVariantId")
                        .HasName("pk_pack_definition_item");

                    b.HasIndex("ItemVariantId")
                        .HasDatabaseName("ix_pack_definition_item_item_variant_id");

                    b.ToTable("pack_definition_item", "public");
                });

            modelBuilder.Entity("Domain.Todos.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.PrimitiveCollection<List<string>>("Labels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("labels");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_todo_items");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_todo_items_user_id");

                    b.ToTable("todo_items", "public");
                });

            modelBuilder.Entity("Domain.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_on_utc");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", "public");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("Domain.Classifications.Category", b =>
                {
                    b.HasOne("Domain.Classifications.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_category_category_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Classifications.Tag", b =>
                {
                    b.HasOne("Domain.Inventories.Inventory", null)
                        .WithMany("Tags")
                        .HasForeignKey("InventoryId")
                        .HasConstraintName("fk_tag_inventory_inventory_id");

                    b.HasOne("Domain.Inventories.InventoryItem", null)
                        .WithMany("Tags")
                        .HasForeignKey("InventoryItemId")
                        .HasConstraintName("fk_tag_inventory_item_inventory_item_id");

                    b.HasOne("Domain.Items.ItemDefinition", null)
                        .WithMany("Tags")
                        .HasForeignKey("ItemDefinitionId")
                        .HasConstraintName("fk_tag_item_definition_item_definition_id");

                    b.HasOne("Domain.Items.ItemVariant", null)
                        .WithMany("Tags")
                        .HasForeignKey("ItemVariantId")
                        .HasConstraintName("fk_tag_item_variant_item_variant_id");

                    b.HasOne("Domain.Items.PackDefinition", null)
                        .WithMany("Tags")
                        .HasForeignKey("PackDefinitionId")
                        .HasConstraintName("fk_tag_pack_definition_pack_definition_id");
                });

            modelBuilder.Entity("Domain.Classifications.TagAssignment", b =>
                {
                    b.HasOne("Domain.Classifications.Tag", "Tag")
                        .WithMany("Assignments")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tag_assignment_tag_tag_id");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Domain.Inventories.Inventory", b =>
                {
                    b.HasOne("Domain.Classifications.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_category_category_id");

                    b.HasOne("Domain.Inventories.Inventory", "ParentInventory")
                        .WithMany("ChildInventories")
                        .HasForeignKey("ParentInventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_inventory_parent_inventory_id");

                    b.Navigation("Category");

                    b.Navigation("ParentInventory");
                });

            modelBuilder.Entity("Domain.Inventories.InventoryItem", b =>
                {
                    b.HasOne("Domain.Classifications.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_item_category_category_id");

                    b.HasOne("Domain.Inventories.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_item_inventory_inventory_id");

                    b.HasOne("Domain.Items.ItemVariant", "ItemVariant")
                        .WithMany("InventoryItems")
                        .HasForeignKey("ItemVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_item_item_variant_item_variant_id");

                    b.HasOne("Domain.Items.PackDefinition", "PackDefinition")
                        .WithMany("InventoryItems")
                        .HasForeignKey("PackDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_item_pack_definition_pack_definition_id");

                    b.Navigation("Category");

                    b.Navigation("Inventory");

                    b.Navigation("ItemVariant");

                    b.Navigation("PackDefinition");
                });

            modelBuilder.Entity("Domain.Items.ItemDefinition", b =>
                {
                    b.HasOne("Domain.Classifications.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_item_definition_category_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Items.ItemVariant", b =>
                {
                    b.HasOne("Domain.Classifications.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_item_variant_category_category_id");

                    b.HasOne("Domain.Items.ItemDefinition", "ItemDefinition")
                        .WithMany("Variants")
                        .HasForeignKey("ItemDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_item_variant_item_definition_item_definition_id");

                    b.Navigation("Category");

                    b.Navigation("ItemDefinition");
                });

            modelBuilder.Entity("Domain.Items.PackDefinition", b =>
                {
                    b.HasOne("Domain.Classifications.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pack_definition_category_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Items.PackDefinitionItem", b =>
                {
                    b.HasOne("Domain.Items.ItemVariant", "ItemVariant")
                        .WithMany("Packs")
                        .HasForeignKey("ItemVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pack_definition_item_item_variant_item_variant_id");

                    b.HasOne("Domain.Items.PackDefinition", "PackDefinition")
                        .WithMany("Items")
                        .HasForeignKey("PackDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pack_definition_item_pack_definition_pack_definition_id");

                    b.Navigation("ItemVariant");

                    b.Navigation("PackDefinition");
                });

            modelBuilder.Entity("Domain.Todos.TodoItem", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_items_users_user_id");
                });

            modelBuilder.Entity("Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Classifications.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Domain.Classifications.Tag", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Domain.Inventories.Inventory", b =>
                {
                    b.Navigation("ChildInventories");

                    b.Navigation("Items");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Domain.Inventories.InventoryItem", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Domain.Items.ItemDefinition", b =>
                {
                    b.Navigation("Tags");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Domain.Items.ItemVariant", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("Packs");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Domain.Items.PackDefinition", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("Items");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
